#BuildTemplates
# File:two_apps_buildAndPublish.yaml

parameters:
  - name: azureAgentPool
    type: string #"Azure Cloud Test Agent Pool"
  - name: solution_1
    type: string
  - name: solution_2
    type: string
  - name: binarys_Path_1
    type: string
  - name: binarys_Path_2
    type: string
  - name: artifact_name_1
    default: 'web' 
  - name: artifact_name_2
    default: 'web' 
  - name: environment
    default: DES
    values:
      - DES
      - TST
  - name: build_type_1
    default: MsBuild
    values:
      - Core5
      - MsBuild
  - name: build_type_2
    default: MsBuild
    values:
      - Core5
      - MsBuild
  - name: deploy_type_1
    default: Web
    values:
      - Web
      - Sql
      - Console
  - name: deploy_type_2
    default: Web
    values:
      - Web
      - Sql
      - Console
  - name: BuildConfiguration
    default: 'Release'
  - name: buildPlatform
    default: 'Any CPU' 

jobs:
- job: Build_Publish_App1
  pool:
    name: ${{ parameters.azureAgentPool }}
  steps:
  # Only when Build & Publish on Web:
  - ${{ if eq(parameters.deploy_type_1, 'Web') }}:
     - ${{ if eq(parameters.build_type_1, 'Core5') }}:   # Build & Publish on WEB CORE5:

        - task: NuGetCommand@2
          displayName: NuGetCommand Web Core5
          inputs:
            solution: ${{ parameters.solution_1 }}

        - task: DotNetCoreCLI@2
          displayName: Restore Web Core5
          inputs:
            command: restore
            projects: ${{ parameters.solution_1 }}

        - task: DotNetCoreCLI@2
          displayName: Build Web Core5
          inputs:
            projects: ${{ parameters.solution_1 }}
            arguments: '--configuration ${{ parameters.BuildConfiguration }}'
          
        - task: DotNetCoreCLI@2
          displayName: Test Web Core5
          inputs:
            command: test
            projects: ${{ parameters.solution_1 }}
            arguments: '--configuration ${{ parameters.BuildConfiguration }}'

        - task: DotNetCoreCLI@2
          displayName: Publish Web Core5
          inputs:
            command: publish
            publishWebProjects: false
            projects: ${{ parameters.solution_1 }}
            arguments: '--configuration ${{ parameters.BuildConfiguration }} --output $(build.artifactstagingdirectory)'
            zipAfterPublish: false
            modifyOutputPath: false
    
        - task: PublishPipelineArtifact@1
          displayName: PublishPipelineArtifact Web Core5
          inputs:
            targetPath: '$(build.artifactstagingdirectory)'
            artifactName: ${{ parameters.artifact_name_1 }}

     - ${{ if eq(parameters.build_type_1, 'MsBuild') }}:     # Build & Publish on Web MsBuild:

        - task: NuGetCommand@2
          displayName: NuGetCommand Web MsBuild
          inputs:
            solution: ${{ parameters.solution_1 }}
            
        - task: MSBuild@1
          displayName: "Build Web MsBuild"
          inputs:
            solution: ${{ parameters.solution_1 }}
            platform: '${{ parameters.buildPlatform }}'
            configuration: '${{ parameters.BuildConfiguration }}'
            msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
        
        - task: PublishPipelineArtifact@1
          displayName: PublishPipelineArtifact Web MsBuild 
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)\${{ parameters.binarys_Path_1 }}\obj\${{ parameters.BuildConfiguration }}\Package\PackageTmp\'
            artifact: ${{ parameters.artifact_name_1 }}
            publishLocation: "pipeline"

  # Only when build and publish on CONSOLE:
  - ${{ if eq(parameters.deploy_type_1, 'Console') }}:
    - ${{ if eq(parameters.build_type_1, 'Core5') }}:    # Build & Publish on CONSOLE CORE5:

       - task: NuGetCommand@2
         displayName: NuGetCommand Console Core5
         inputs:
           solution: ${{ parameters.solution_1 }}
         
       - task: DotNetCoreCLI@2
         displayName: Restore Console Core5
         inputs:
           command: restore
           projects: ${{ parameters.solution_1 }}
    
       - task: DotNetCoreCLI@2
         displayName: DotNet Build Console Core5
         inputs:
           projects: ${{ parameters.solution_1 }}
           arguments: '--configuration ${{ parameters.BuildConfiguration }}'

       - task: DotNetCoreCLI@2
         displayName: Publish Console Core5
         inputs:
           command: publish
           publishWebProjects: false
           projects: ${{ parameters.solution_1 }}
           arguments: '--configuration ${{ parameters.BuildConfiguration }} --output $(build.artifactstagingdirectory)'
           zipAfterPublish: false
           modifyOutputPath: false

       - task: PublishPipelineArtifact@1
         displayName: PublishPipelineArtifact Console Core5
         inputs:
           targetPath: '$(build.artifactstagingdirectory)'
           artifactName: ${{ parameters.artifact_name_1 }}

    - ${{ if eq(parameters.build_type_1, 'MsBuil') }}:     # Build & Publish on CONSOLE MSBUILD:

       - task: NuGetCommand@2
         displayName: NuGetCommand Console Core5
         inputs:
           solution: ${{ parameters.solution_1 }}

    # Only when build and publish on SQL:
  - ${{ if eq(parameters.deploy_type_1, 'Sql') }}:
   
     - task: NuGetCommand@2
       displayName: NuGetCommand SQL
       inputs:
         solution: ${{ parameters.solution_1 }}
            
     - task: MSBuild@1
       displayName: "Build SQL"
       inputs:
         solution: ${{ parameters.solution_1 }}
         msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'

     - task: PublishPipelineArtifact@1
       displayName: PublishPipelineArtifact SQL
       inputs:
         targetPath: '$(System.DefaultWorkingDirectory)\${{ parameters.binarys_Path_1 }}\bin\'
         artifact: ${{ parameters.artifact_name_1 }}
         publishLocation: "pipeline"

- job: Build_Publish_App2
  pool:
    name: ${{ parameters.azureAgentPool }}
  steps:
  # Only when Build & Publish on WEB:
  - ${{ if eq(parameters.deploy_type_2, 'Web') }}:
     - ${{ if eq(parameters.build_type_2, 'Core5') }}:   # Build & Publish on WEB CORE5:

        - task: NuGetCommand@2
          displayName: NuGetCommand Web Core5
          inputs:
            solution: ${{ parameters.solution_2 }}

        - task: DotNetCoreCLI@2
          displayName: Restore Web Core5
          inputs:
            command: restore
            projects: ${{ parameters.solution_2 }}

        - task: DotNetCoreCLI@2
          displayName: Build Web Core5
          inputs:
            projects: ${{ parameters.solution_2 }}
            arguments: '--configuration ${{ parameters.BuildConfiguration }}'
          
        - task: DotNetCoreCLI@2
          displayName: Test Web Core5
          inputs:
            command: test
            projects: ${{ parameters.solution_2 }}
            arguments: '--configuration ${{ parameters.BuildConfiguration }}'

        - task: DotNetCoreCLI@2
          displayName: Publish Web Core5
          inputs:
            command: publish
            publishWebProjects: false
            projects: ${{ parameters.solution_2 }}
            arguments: '--configuration ${{ parameters.BuildConfiguration }} --output $(build.artifactstagingdirectory)'
            zipAfterPublish: false
            modifyOutputPath: false
    
        - task: PublishPipelineArtifact@1
          displayName: PublishPipelineArtifact Web Core5
          inputs:
            targetPath: '$(build.artifactstagingdirectory)'
            artifactName: ${{ parameters.artifact_name_2 }}

     - ${{ if eq(parameters.build_type_2, 'MsBuild') }}:     # Build & Publish on WEB MSBUILD:

        - task: NuGetCommand@2
          displayName: NuGetCommand Web MsBuild
          inputs:
            solution: ${{ parameters.solution_2 }}
            
        - task: MSBuild@1
          displayName: "Build Web MsBuil"
          inputs:
            solution: ${{ parameters.solution_2 }}
            platform: '${{ parameters.buildPlatform }}'
            configuration: '${{ parameters.BuildConfiguration }}'
            msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
        
        - task: PublishPipelineArtifact@1
          displayName: PublishPipelineArtifact Web MsBuild 
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)\${{ parameters.binarys_Path_2 }}\obj\${{ parameters.BuildConfiguration }}\Package\PackageTmp\'
            artifact: ${{ parameters.artifact_name_2 }}
            publishLocation: "pipeline"

  # Only when build and publish on CONSOLE:
  - ${{ if eq(parameters.deploy_type_2, 'Console') }}:
    - ${{ if eq(parameters.build_type_2, 'Core5') }}:    # Build & Publish on CONSOLE CORE5:

       - task: NuGetCommand@2
         displayName: NuGetCommand Console Core5
         inputs:
           solution: ${{ parameters.solution_2 }}
         
       - task: DotNetCoreCLI@2
         displayName: Restore Console Core5
         inputs:
           command: restore
           projects: ${{ parameters.solution_2 }}
    
       - task: DotNetCoreCLI@2
         displayName: DotNet Build Console Core5
         inputs:
           projects: ${{ parameters.solution_2 }}
           arguments: '--configuration ${{ parameters.BuildConfiguration }}'

       - task: DotNetCoreCLI@2
         displayName: Publish Console Core5
         inputs:
           command: publish
           publishWebProjects: false
           projects: ${{ parameters.solution_2 }}
           arguments: '--configuration ${{ parameters.BuildConfiguration }} --output $(build.artifactstagingdirectory)'
           zipAfterPublish: false
           modifyOutputPath: false

       - task: PublishPipelineArtifact@1
         displayName: PublishPipelineArtifact Console Core5
         inputs:
           targetPath: '$(build.artifactstagingdirectory)'
           artifactName: ${{ parameters.artifact_name_2 }}

    - ${{ if eq(parameters.build_type_2, 'MsBuild') }}:     # Build & Publish on CONSOLE MSBUILD:

       - task: NuGetCommand@2
         displayName: NuGetCommand Console Core5
         inputs:
           solution: ${{ parameters.solution_2 }}

    # Only when build and publish on SQL:
  - ${{ if eq(parameters.deploy_type_2, 'Sql') }}:
   
     - script: echo "${{ parameters.solution_1 }} ,${{ parameters.solution_2 }} "
     - task: NuGetCommand@2
       displayName: NuGetCommand SQL
       inputs:
         solution: ${{ parameters.solution_2 }}
            
     - task: MSBuild@1
       displayName: "Build SQL"
       inputs:
         solution: ${{ parameters.solution_2 }}
         msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'

     - task: PublishPipelineArtifact@1
       displayName: PublishPipelineArtifact SQL
       inputs:
         targetPath: '$(System.DefaultWorkingDirectory)\${{ parameters.binarys_Path_2 }}\bin\'
         artifact: ${{ parameters.artifact_name_2 }}
         publishLocation: "pipeline"
    
    